#################################################
# HyperProtectBackendSDK - Ansible
#################################################
---
- name: Configure Hyper Protect Virtual Server
  hosts: all
  become: true
  tasks:
    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'curl', 'npm', 'docker.io', 'ufw', 'docker-compose', 'git' ]
      ignore_errors: true

    - name: Clone github repo (SDK CareKit)
      git:
          repo: https://github.com/carekit-apple/IBM-HyperProtectMBaaS.git
          dest: ~/IBM-HyperProtectMBaaS

    - name: "Create file on HPVS container for .env test"
      copy:
          content: "MONGO_DB={{ db }}"
          dest: ~/HyperProtectBackendSDK-test/.env

    - name: Copy 'cert.pem' file from local to Virtual Server
      copy:
          src: "{{ playbook_dir }}/cert.pem"
          dest: ~/HyperProtectBackendSDK-test/src/


    - name: Running setup via docker-compose.yml
      docker_compose:
          project_src: /root/IBM-HyperProtectMBaaS
