#################################################
# HyperProtectBackendSDK - Ansible
#################################################
---
- name: Configure Hyper Protect Virtual Server
  hosts: all
  become: true
  tasks:
    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'curl', 'npm', 'docker.io', 'ufw', 'docker-compose', 'git' ]
      ignore_errors: true

    - name: Clone github repo (SDK CareKit)
      git:
          repo: https://github.com/Ry-is-me/HyperProtectBackendSDK-test.git
          dest: ~/HyperProtectBackendSDK-test

    - name: "Create file on HPVS container for .env test"
      copy:
          content: "MONGO_DB={{ db }}"
          dest: ~/HyperProtectBackendSDK-test/.env

    - name: Copy 'cert.pem' file from local to Virtual Server
      copy:
          src: "{{ playbook_dir }}/cert.pem"
          dest: ~/HyperProtectBackendSDK-test/src/


    - name: Run 'generate_certs' script for SSL certificates
      shell: "bash ~/HyperProtectBackendSDK-test/generate_certs.sh {{ inventory_hostname }}"
      ignore_errors: true

    - pause: seconds=90


    - name: Running setup via docker-compose.yml
      docker_compose:
          project_src: /root/HyperProtectBackendSDK-test

    - pause: seconds=20

    - name:
      shell: "bash ~/HyperProtectBackendSDK-test/copy_cert.sh"

    - name: Copy rootCA.crt to local machine for validation test with curl/browser
      fetch:
        src: /root/rootCA.crt
        dest: "{{ playbook_dir }}/"
        mode: 0774
        flat: yes
